version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=501
      - PGID=999
    volumes:
      - /mnt/STORAGE/docker-volumes/unifi/config/:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    mem_limit: 4096m
    restart: unless-stopped
